# Generated by Django 4.1.6 on 2023-03-23 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('House_name', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('decription', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('Address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_user.address')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourtCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Legalscrutiny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NotaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Todo_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Progress', 'Progress'), ('Close', 'Close')], default=1, max_length=10)),
                ('Address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_user.address')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_user.notarycategory')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_user.client')),
            ],
        ),
        migrations.CreateModel(
            name='Legalscrutiny_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_user.legalscrutiny')),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_user.courtcategory')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_user.client_category'),
        ),
        migrations.CreateModel(
            name='CaseRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('case_number', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('incident', models.CharField(max_length=50, null=True)),
                ('Filling_Date', models.DateField(null=True)),
                ('First_hearing_date', models.DateField(null=True)),
                ('Next_hearing_date', models.DateField(null=True)),
                ('Fir_date', models.DateField(null=True)),
                ('Fir_number', models.IntegerField(null=True)),
                ('Fir_policeStation', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('1', 'open'), ('2', 'judgement'), ('3', 'closed')], default=1, max_length=20, null=True)),
                ('advocate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_user.advocate')),
                ('case_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_user.casecategory')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_user.client')),
            ],
        ),
        migrations.CreateModel(
            name='CaseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'created'), ('updated', 'updated'), ('closed', 'closed')], default=1, max_length=50)),
                ('date', models.DateField(null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Admin_user.caseregister')),
            ],
        ),
        migrations.AddField(
            model_name='advocate',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_user.court'),
        ),
    ]
