# Generated by Django 4.1.6 on 2023-03-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notary',
            name='status',
        ),
        migrations.AddField(
            model_name='notary',
            name='file',
            field=models.FileField(default='tfytd', max_length=1000, upload_to='notary'),
            preserve_default=False,
        ),
    ]
