# Generated by Django 4.1.6 on 2023-03-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_user', '0002_remove_notary_status_notary_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
