# Generated by Django 4.1.6 on 2023-03-26 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_user', '0003_district_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Admin_user.state'),
            preserve_default=False,
        ),
    ]
