# Generated by Django 4.1.6 on 2023-03-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_user', '0004_district_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(default=53, on_delete=django.db.models.deletion.CASCADE, to='Admin_user.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_user.state'),
        ),
    ]
