# Generated by Django 4.1.6 on 2023-03-27 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_user', '0005_address_district_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Admin_user.address'),
        ),
    ]
