# Generated by Django 4.1.6 on 2023-02-11 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_user', '0005_legalscrutiny_legalscrutiny_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('decription', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='caseregister',
            name='case_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_user.casecategory'),
        ),
    ]
