# Generated by Django 4.1.6 on 2023-03-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_user', '0006_alter_advocate_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
