# Generated by Django 4.1.6 on 2023-03-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_user', '0007_alter_client_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_case',
            field=models.BooleanField(default=False),
        ),
    ]
