# Generated by Django 4.1.6 on 2023-03-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_user', '0008_client_is_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('types', models.CharField(max_length=50)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_user.address')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_user.caseregister')),
            ],
        ),
    ]
