# Generated by Django 4.1.6 on 2023-03-31 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_user', '0009_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='caseSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_user.sections')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_user.caseregister')),
            ],
        ),
    ]
