# Generated by Django 4.1.6 on 2023-04-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_user', '0010_sections_casesections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseregister',
            name='address',
        ),
    ]
