# Generated by Django 4.1.6 on 2023-05-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_user', '0013_judgement_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='specialization',
            field=models.CharField(default='Criminal', max_length=60),
        ),
    ]
