from django.urls import path,include
from .views import *
urlpatterns = [
    path("login/",login),
    path("home",home),
    path("",home),
    path("logout",logout),
    path("addadvocate",add_advocate),
    path("viewadvocates",view_advocate),
    path("removeadvocate/<int:id>",remove_advocate),
    path("addcase",add_case,name="add_case_category"),
    path("test",test),
    path("contact",contact,name="contact"),
    path("contact/category",contact_category,name="contact_category"),
    path("client",client,name="client"),
    path("client/category",client_category,name="client_category"),
    path("case",case,name="case"),
    path("case/add",addcase,name="add_case"),
    path("case/category",case_category,name="case_category"),
    path("case/judgement",judgement_case,name="judgement_case"),
    path("case/closed",closed_case,name="closed_case"),
    path("notary",notary,name="notary"),
    path("notary/open",open_notary,name="open_notary"),
    path("notary/closed",closed_notary,name="closed_notary"),
    path("notary/add",add_notary,name="add_notary"),
    path("scrutiny/clients",legal_scrutiny_clients,name="legal_scrutiny_clients"),
    path("scrutiny/client/add",legal_scrutiny_add_clients,name="legal_scrutiny_add_clients"),
    path("scrutiny/add/appointments",legal_scrutiny_add_appointmends,name="legal_scrutiny_add_appointmends"),
    path("court/list",court_list,name="court_list"),
    path("court/add",add_court,name="add_court"),
    path("court/category",court_category,name="court_category"),
    path("court/cateory/add",add_court_category,name="add_court_category"),
    path("todo",todo_list,name="todo_list")
]
